[package]
name = "teatro"
version = "0.1.0"
authors = ["Jens Reidel <jens@troet.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
actix-web = { version = "3", default-features = false, features = ["rustls"] }
bb8-redis = "0.5"
bb8-postgres = "0.4"
env_logger = "0.7"
rand = "0.7"
serde = "1"
serde_json = "1"

[profile.release]
lto = true
